call W:\Tools\Sign\sign.bat "Translation" "German.dll"
call W:\Tools\Sign\sign.bat "Translation" "French.dll"
call W:\Tools\Sign\sign.bat "Translation" "Italian.dll"
call W:\Tools\Sign\sign.bat "Translation" "Russian.dll"
call W:\Tools\Sign\sign.bat "Translation" "Spanish.dll"
call W:\Tools\Sign\sign.bat "Translation" "Portuguese.dll"
call W:\Tools\Sign\sign.bat "Translation" "Japanese.dll"
call W:\Tools\Sign\sign.bat "Translation" "Chinese (Simplified), Simplified.dll"

call W:\Tools\Sign\sign.bat "Translation" "Polish.dll"
call W:\Tools\Sign\sign.bat "Translation" "Turkish.dll"
call W:\Tools\Sign\sign.bat "Translation" "Hindi.dll"
call W:\Tools\Sign\sign.bat "Translation" "Persian.dll"
call W:\Tools\Sign\sign.bat "Translation" "Urdu.dll"
call W:\Tools\Sign\sign.bat "Translation" "Bengali.dll"
call W:\Tools\Sign\sign.bat "Translation" "Arabic.dll"
